In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
import pandas as pd

matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2x3 = np.array([[1, 2, 4], [4, 5, 6]])

print('3 x 2 matrix : \n', matrix3x2)
print('\n 2 x 3 matrix : \n', matrix2x3)

3 x 2 matrix : 
 [[1 2]
 [3 4]
 [5 6]]

 2 x 3 matrix : 
 [[1 2 4]
 [4 5 6]]


In [4]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.44117636 0.55370394 0.54110279 0.48818678]
 [0.81304169 0.35240217 0.5908521  0.39402614]
 [0.16442988 0.30135158 0.26293906 0.82833167]]


In [5]:
# matrix multiplication
matmul = np.dot(matrix3x2, matrix2x3)
print(matmul)

[[ 9 12 16]
 [19 26 36]
 [29 40 56]]


In [6]:
# elemet wise matrix multiplication
result = [[0 for x in range(len(matrix3x2))] for y in range(len(matrix2x3[0]))]

for i in range(len(matrix3x2)): 
  for j in range(len(matrix2x3[0])): 
    for k in range(len(matrix2x3)): 
      result[i][j] += matrix3x2[i][k] * matrix2x3[k][j]
 
print('Element wise multiplication : \n', result)

Element wise multiplication : 
 [[9, 12, 16], [19, 26, 36], [29, 40, 56]]


In [7]:
mean = np.mean(matrix3x2)
print(mean)

3.5


In [8]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML Labs/Lab 1/mtcars.csv')

In [9]:
del data['model']

meancenter = data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
